from nld.utils import NldStrEnum


class FlowExecStatus(NldStrEnum):
    SUCCEEDED = "SUCCEEDED"
    SUCCEEDED_WITH_WARNING = "WARNING"
    ON_GOING = "ONGOING"
    FAILED = "FAILED"


class FlowStepCategory(NldStrEnum):
    FLOW_EXECUTION = "FLOW_EXECUTION"
    POST_HOOK = "POST_HOOK"
    POST_PROCESSING_FOR_STATE = "POST_PROCESSING_FOR_STATE"
    PRE_HOOK = "PRE_HOOK"
    PRE_PROCESSING_FOR_STATE = "PRE_PROCESSING_FOR_STATE"
    TECHNICAL_METADATA = "TECHNICAL_METADATA"


class FlowStepExecStatus(NldStrEnum):
    SUCCEEDED = "SUCCEEDED"
    SUCCEEDED_WITH_WARNING = "WARNING"
    FAILED = "FAILED"
